const GET_POKEMONS = "GET_POKEMONS";
const GET_POKEMON_BY_ID = "GET_POKEMON"
const GET_TYPES = "GET_TYPES"
const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME"

export { GET_POKEMONS, GET_POKEMON_BY_ID, GET_TYPES, GET_POKEMON_BY_NAME };
