const GET_POKEMONS = "GET_POKEMONS";
const GET_POKEMON_BY_ID = "GET_POKEMON";
const GET_TYPES = "GET_TYPES";
const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";
const FILTER_A_Z = "FILTER_A_Z";
const FILTER_Z_A = "FILTER_Z_A";
const FILTER_CREATED = "FILTER_CREATED";
const FILTER_MAX_MIN = "FILTER_MAX_MIN";
const FILTER_MIN_MAX = "FILTER_MIN_MAX";

export {
  GET_POKEMONS,
  GET_POKEMON_BY_ID,
  GET_TYPES,
  GET_POKEMON_BY_NAME,
  FILTER_A_Z,
  FILTER_Z_A,
  FILTER_CREATED,
  FILTER_MAX_MIN,
  FILTER_MIN_MAX
};
